export const LOAD_EMPLOYEE_LIST = 'LOAD_EMPLOYEE_LIST';
export const LOAD_EMPLOYEE_LIST_SUCCESS = 'LOAD_EMPLOYEE_LIST_SUCCESS';
// export const LOAD_CUSTOMER = 'LOAD_CUSTOMER';
// export const LOAD_CUSTOMER_SUCCESS = 'LOAD_CUSTOMER_SUCCESS';
export const UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE';
export const UPDATE_EMPLOYEE_SUCCESS = 'UPDATE_EMPLOYEE_SUCCESS';
